/**
 * DataDog Monitors — hand port of `datadogmonitors/datadog_monitors.star`
 * (by Cavallando), kept structurally line-for-line: same icons, monitor
 * search query, slide-in/slide-out Transformation cadence.
 *
 * Differences from the Starlark original:
 *  - The manual `cache` calls became the http TTL cache (240s, as before).
 *  - A site dropdown (US1/EU/US3/US5) replaces the hardcoded US host.
 *  - Widths/heights derive from config.width()/height() so the layout works
 *    on 64x32, 64x64 and 128x64 (the original hardcoded 100px slide offsets
 *    and a 25px text column).
 *  - With no API keys configured it previews an example triggered monitor
 *    instead of claiming "No issues!".
 */

import {
  animation,
  Box,
  Config,
  Image,
  Root,
  Row,
  Sequence,
  Text,
  Transformation,
  WrappedText,
  schema,
  type RootSpec,
  type Schema,
  type WidgetSpec,
} from "@koiosdigital/matrx-sdk";
import { http } from "@koiosdigital/matrx-sdk/stdlib";

import CHECK_ICON from "./check.png";
import ALERT_ICON from "./alert.png";

const DEFAULT_QUERY = "status:alert";
const DATA_TTL_SECONDS = 240;

const SITE_HOSTS: Record<string, string> = {
  us1: "api.datadoghq.com",
  eu: "api.datadoghq.eu",
  us3: "api.us3.datadoghq.com",
  us5: "api.us5.datadoghq.com",
};

interface MonitorSearch {
  monitors?: { name?: string }[] | null;
}

const EXAMPLE_DATA: MonitorSearch = {
  monitors: [{ name: "Example monitor - add your DataDog API keys" }],
};

export default async function render(config: Config): Promise<RootSpec> {
  const apiKey = config.get("api_key") || null;
  const appKey = config.get("app_key") || null;
  const monitorsQuery = config.str("custom_query", DEFAULT_QUERY);
  const host = SITE_HOSTS[config.get("site", "us1")!] ?? SITE_HOSTS.us1;

  const width = config.width();
  const height = config.height();

  let data: MonitorSearch;
  if (apiKey !== null && appKey !== null) {
    const res = await http.get(`https://${host}/api/v1/monitor/search`, {
      params: { query: monitorsQuery },
      headers: {
        "DD-API-KEY": apiKey,
        "DD-APPLICATION-KEY": appKey,
        Accept: "application/json",
      },
      ttlSeconds: DATA_TTL_SECONDS,
    });
    data = res.status === 200 ? (res.json() as MonitorSearch) : {};
  } else {
    data = EXAMPLE_DATA;
  }

  const iconSize = height >= 64 ? 24 : 18;
  const textWidth = width - iconSize - 4;

  let child: WidgetSpec;
  if (!data.monitors) {
    child = Row({
      crossAlign: "center",
      mainAlign: "center",
      children: [
        Image({ src: ALERT_ICON, width: iconSize, height: iconSize }),
        WrappedText({
          align: "center",
          content: "Could not connect to DataDog",
          width: textWidth,
        }),
      ],
    });
  } else if (data.monitors.length > 0) {
    // Slide each triggered monitor in from the left, hold, slide out right.
    const keyframes = [
      animation.Keyframe({ percentage: 0.0, transforms: [animation.Translate(-width, 0)], curve: "linear" }),
      animation.Keyframe({ percentage: 0.25, transforms: [animation.Translate(0, 0)], curve: "linear" }),
      animation.Keyframe({ percentage: 0.75, transforms: [animation.Translate(0, 0)], curve: "linear" }),
      animation.Keyframe({ percentage: 1, transforms: [animation.Translate(width, 0)], curve: "linear" }),
    ];
    const children = data.monitors.map((monitor) =>
      Transformation({
        duration: 150,
        child: Box({
          width: textWidth,
          height,
          child: WrappedText({
            width: textWidth,
            content: monitor.name ?? "Monitor Triggered",
          }),
        }),
        keyframes,
      }),
    );
    child = Row({
      expanded: false,
      mainAlign: "center",
      crossAlign: "center",
      children: [
        Box({
          width: iconSize,
          height: iconSize,
          child: Image({ src: ALERT_ICON, width: iconSize, height: iconSize }),
        }),
        Sequence({ children }),
      ],
    });
  } else {
    child = Row({
      expanded: true,
      crossAlign: "center",
      mainAlign: "center",
      children: [
        Box({ width: iconSize + 2, child: Image({ src: CHECK_ICON, width: iconSize, height: iconSize }) }),
        Text({ content: "No issues!" }),
      ],
    });
  }

  return Root({ child });
}

export function getSchema(): Schema {
  return schema.schema({
    version: "1",
    fields: [
      schema.text({
        id: "api_key",
        name: "DataDog API Key",
        desc: "API Key from your settings",
        icon: "lock",
        default: "",
      }),
      schema.text({
        id: "app_key",
        name: "DataDog Application Key",
        desc: "A DataDog user account Application Key generated by the user",
        icon: "lock",
        default: "",
      }),
      schema.dropdown({
        id: "site",
        name: "DataDog Site",
        desc: "The DataDog site your organization lives on.",
        icon: "globe",
        default: "us1",
        options: [
          schema.option({ display: "US1 (datadoghq.com)", value: "us1" }),
          schema.option({ display: "EU (datadoghq.eu)", value: "eu" }),
          schema.option({ display: "US3", value: "us3" }),
          schema.option({ display: "US5", value: "us5" }),
        ],
      }),
      schema.text({
        id: "custom_query",
        name: "Override Query",
        desc: "Override completely searching for monitors",
        icon: "magnifyingGlass",
        default: DEFAULT_QUERY,
      }),
    ],
  });
}
